// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ojvfnxciphvfnxcsraug.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qdmZueGNpcGh2Zm54Y3NyYXVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MDY0NTcsImV4cCI6MjA1OTA4MjQ1N30.1gdWsgujECzVRJhkRcXwMX5P--B5EkYclX7u073veu0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);